#pragma once
#include "Test_01_SkyBox.h"   
#include "Test_02_ShadowMap.h"
#include "Test_03_DefferedShading.h"
#include "Test_04_SSAO.h"
#include "Test_05_Bloom.h"
#include "Test_06_NormalMap.h"
#include "Test_07_3DClickPick.h"
#include "Test_PBR.h"